name: Redmine

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Setup System
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev

    - name: Redmine plugin test
      uses: two-pack/redmine-plugin-test-action@v1
      with:
        plugin-name: redmine_xapian
        redmine_version: 4.1-stable
